---
name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: 27.1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - run: ./bin/tangle -l - -v --no-interactive
    # TODO maybe test you can start and install plugins
    # I'm worried about spamming MELPA with every commit
    # tho :/.
